### PR TITLE
Include the user testing questionnaire in the footer (300)

### LINKED ISSUE #300: Mention user testing in the footer
Next to "Report a bug on this site" can we have:

"Help us improve the platform, [participate in user testing](https://docs.google.com/forms/d/e/1FAIpQLSfCbGjGlCHCx3CdjH6Ls2nPd37nWFzlBoVXq1hAC9V9cYz2AA/viewform)"

### PR DESCRIPTION
**Pull request by evandandrea**
Fixes #300.

### CODE REVIEW

**Comment by caldav** [comment]
Holding on, waiting on the merge of its b.s.io counterpart.

**Comment by anthonydillon** [comment]
@evandandrea Is this PR blocked at the moment?

**Comment by matthewpaulthomas** [comment]
@anthonydillon According to #745, build.snapcraft.io is still in beta; therefore it’s still showing the beta survey; therefore it isn’t showing a second survey at the same time; therefore snapcraft.io isn’t showing the survey either. I guess this is blocked as long as all of those “therefore”s are valid.

**Comment by anthonydillon** [comment]
@matthewpaulthomas Thank you, can we close this PR until we are ready to publish the second survey?

**Comment by matthewpaulthomas** [comment]
@anthonydillon I’m not a GitHub expert, so I’m not aware of any benefit in closing a PR only to open an identically-functioning one later. A drawback is that you might forget to do it. I guess the next step for unblocking this is for @evandandrea to specify when the beta period will end: is it on a particular date, or is it when a particular feature (like private repos) is implemented?

Meanwhile, the issues I identified in the form itself all remain.

**Comment by anthonydillon** [comment]
This is purely because I monitor the PR list regularly and like to get the
number down as low as possible.

**Comment by matthewpaulthomas** [comment]
@anthonydillon That’s a good goal, but closing this PR would then become an example of [Goodhart’s Law](https://en.wikipedia.org/wiki/Goodhart%27s_law). An alternative would be tweaking your metric to “PRs that aren’t labelled as Blocked”.

**Comment by anthonydillon** [comment]
A Blocked label works for me. With a description of the dependency so I
know it is still truly blocked.

**Comment by nottrobin** [comment]
Sorry @evandandrea this repo is now dead. If this is still relevant, please re-submit it over at https://github.com/canonical-websites/snapcraft.io. Sorry for the inconvenience.

**Pull request closed without merging**
